@startuml
title autologin using cashed login info (PouchDB)

start

if (parallel process) then

 if (load auth data
   from local DB) then (false)
  :failure message;
  stop

 else (true)
 :success;
 endif

else
  : load caseList
   from local DB;
  :success;

endif

if (lastUser not exists) then (true)
    :loginStatus = 0;
else if (user != null &&
  caseId != null) then (true)
    :set user & caseId
      to $store;
    :loginStatus = 1;
    if (user & caseId exists
     in caseList) then (true)

    else (false)
      :initialize userData
        for caseId;
      :set userData
       to PouchDB-userDB;
      :reload ceseId list
        from PouchDB;
    endif
else if (user != null) then (yes)
    :set user to $store;
    :loginStatus = 2;
else if (caseId != null) then (true)
    :set caseId to $store;
    :loginStatus = 3;
else (false)
    :loginStatus = 4;
endif

if (loginStatus == 1) then (no)
  :move to '/index';
  :wait for manual login
   (using firebase);
  stop
else (yes)
  :move to desired
   direction;
endif
stop

@enduml
