@startuml
title login through firebase

start

:(params)
 user
 caseId;

:login using firebase;
if (get credential) then (true)
  package "set $store" {
    :merge credential
      with user info;
    :set user
     to $store;
    :set caseId
     to $store;
  }
else (false)
  :failure message;
  :stay @loginPage;
  stop
endif

package "set pouchDB" {
  :set user & caseId to
   PouchDB-lastUser;

  if (user & caseId exists
   in caseList) then (true)

  else (false)
    :initialize userData
      for caseId;
    :set userData
     to PouchDB-userDB;
  endif
}

:move to '/index';

stop

@enduml
