@startuml
title login through firebase

start

:(params)
 user
 caseId;
:login using firebase;
if (get credential?) then (true)
  package "set user" {
    :merge credential
      with user info;
    :set user
     to $store;
  }
else (false)
  :failure message;
  :stay @loginPage;
  stop
endif
  :select caseId from
   selectWorkspace;
package "set caseId" {
   if (new caseId?) then (false)
     :set caseId
      to $store;
     :set user & caseId to
      lastUser_DB;
     :get userData from
       userData_DB;
     :set userData
       to $store;
   else (true)
     :set caseId
      to $store;
     :set user & caseId
       to $store;
   package "initialize userData" {
     :initialize userData
      for caseId;
     :set userData
      to userData_DB;
   }
   :set userData
     to $store;

  endif
}
:move to '/index';
stop

@enduml
