@startuml
title user registration (firebase with pouchDB)

start

:set user information
   and caseId;

:send user to firebase;

 if (get credential) then (yes)
  :user check;
   if (already exists) then (new user)
    package "user registration"{
    :merge credential
    with user info;
    :save user & caseId
     to $store;
    :save user & caseId
     to lastUser_pouchDB;
    }
    package "initialization"{
    :initialize userData
      linked with caseId;
    :set userData
     to userDB_PouchDB;
    }
    :move to /index;
     stop

   else (existing user)
     :user duplicate;
   endif
 else (no)
   :no credential;
 endif
    :failure message;
    :stay current page;
 stop

@enduml
